spring:
  application:
    name: api-gateway-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: '${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}'

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true

          routes:
            - id: firstService
              uri: lb://first-service-from-config-files-repo
              predicates:
                - Path=/first/**
              -filters:
                - StripPrefix=1
            - id: userService
              uri: lb://user-service-modified
              predicates:
                - Path=/user/**
              -filters:
                - StripPrefix=1

