# Eureka server configuration
eureka.client:
  register-with-eureka: true
  fetch-registry: true
  # Eureka server URL
  service-url.defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}
