spring:
  application:
    name: first-service-from-config-files-repo

server:
  port: 8081


user-service-modified:
  ribbon:
    enabled: false

loadbalancer:
  client:
    name: user-service-modified
